# Generated by Django 3.1.1 on 2020-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
