# Generated by Django 3.1.1 on 2020-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0002_auto_20201022_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='currentlevel',
            field=models.IntegerField(default=0),
        ),
    ]
