# Generated by Django 3.1.1 on 2020-10-22 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biscuitsrk', '0003_auto_20201022_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersModel',
            new_name='Participants',
        ),
    ]
