# Generated by Django 3.1.1 on 2020-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0008_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Resp',
        ),
    ]
