# Generated by Django 3.1.1 on 2020-10-24 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0009_auto_20201024_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentleveltime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
