# Generated by Django 3.1.1 on 2020-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0010_profile_currentleveltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
