# Generated by Django 3.1.1 on 2020-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0011_profile_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mostrecentanswer',
            field=models.TextField(null=True),
        ),
    ]
