# Generated by Django 3.1.1 on 2020-10-26 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0012_profile_mostrecentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastanswertime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='result',
            field=models.BooleanField(default=False),
        ),
    ]
