# Generated by Django 2.2.4 on 2020-11-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0013_auto_20201026_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
