# Generated by Django 2.2.4 on 2020-11-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0014_profile_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='result',
            field=models.BooleanField(default=True),
        ),
    ]
