# Generated by Django 3.1.3 on 2020-11-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0017_auto_20201103_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answer_history',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_history',
            field=models.TextField(default=''),
        ),
    ]
