# Generated by Django 3.1.1 on 2020-11-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0018_auto_20201104_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
