# Generated by Django 3.1.1 on 2020-11-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0019_auto_20201105_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answer_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='response_history',
        ),
    ]
