# Generated by Django 3.1.1 on 2020-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuitsrk', '0020_auto_20201105_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currentlevel',
            field=models.IntegerField(default=1),
        ),
    ]
